import { onCall, HttpsError } from 'firebase-functions/v2/https';
import admin from 'firebase-admin';
admin.initializeApp();
const db = admin.firestore();
const signs = ['1','X','2'];
const randomPicks = () => Object.fromEntries(Array.from({length:14},(_,i)=>[String(i+1), signs[Math.floor(Math.random()*3)]]));
async function assertAdmin(uid){ const snap=await db.doc(`users/${uid}`).get(); if(snap.data()?.role!=='admin') throw new HttpsError('permission-denied','Solo admin'); }
export const generateMissingPredictions = onCall(async (req) => { await assertAdmin(req.auth?.uid); const { roundId, participantIds } = req.data; const batch=db.batch(); participantIds.forEach((uid)=>batch.set(db.doc(`rounds/${roundId}/predictions/${uid}`),{userId:uid,picks:randomPicks(),autoGenerated:true,eliminated:true,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})); await batch.commit(); return { created: participantIds.length }; });
