export const SIGNS = ['1', 'X', '2'];
export const emptyPicks = () => Object.fromEntries(Array.from({ length: 14 }, (_, i) => [String(i + 1), '']));
export const randomPicks = () => Object.fromEntries(Array.from({ length: 14 }, (_, i) => [String(i + 1), SIGNS[Math.floor(Math.random() * 3)]]));

export function scoreRound(matches, prediction, currentCopitaId) {
  const picks = prediction?.picks || {};
  let points = 0, segunda = 0, visitors = 0, draws = 0;
  matches.forEach((m) => {
    const ok = m.result && picks[m.order] === m.result;
    if (ok) {
      points += 1;
      if (m.competition === 'Segunda') segunda += 1;
      if (picks[m.order] === '2') visitors += 1;
      if (picks[m.order] === 'X') draws += 1;
    }
  });
  const plenoHit = prediction?.pleno && prediction.pleno === prediction?.roundPlenoResult;
  if (plenoHit) points += 4;
  if (prediction?.autoGenerated) points = points / 2;
  return { userId: prediction.userId, points, segunda, visitors, draws, plenoHit, autoGenerated: !!prediction?.autoGenerated, wasCopita: prediction.userId === currentCopitaId };
}

export function rankRound(scores, manual = {}) {
  return [...scores].sort((a, b) => {
    if (b.points !== a.points) return b.points - a.points;
    if (a.wasCopita !== b.wasCopita) return a.wasCopita ? 1 : -1;
    if (b.segunda !== a.segunda) return b.segunda - a.segunda;
    if (b.visitors !== a.visitors) return b.visitors - a.visitors;
    if (b.draws !== a.draws) return b.draws - a.draws;
    return (manual[a.userId] ?? 999) - (manual[b.userId] ?? 999);
  });
}

export function computeGeneral(users, roundScores = [], seasonScores = {}) {
  return users.map((u) => ({ ...u, totalPoints: (roundScores[u.id] || 0) + (seasonScores[u.id] || 0), seasonPoints: seasonScores[u.id] || 0 }))
    .sort((a, b) => b.totalPoints - a.totalPoints || (b.money || 0) - (a.money || 0) || (b.copitaCount || 0) - (a.copitaCount || 0) || b.seasonPoints - a.seasonPoints);
}

export function scoreSeasonPrediction(pred, results = {}) {
  let points = 0;
  ['champion','pichichi','zarra','leastConceded','topScorerTeam','firstCoachSacked'].forEach((k) => {
    if (pred[k] && pred[k] === results[k]) points += pred.doubleKey === k ? 10 : 5;
  });
  const groups = [['champions',15],['europa',0],['relegation',15],['promotion',15],['rfefDrop',15]];
  groups.forEach(([k, bonus]) => {
    const p = pred[k] || [], r = results[k] || [];
    let exact = true;
    p.forEach((team, i) => { if (r.includes(team)) points += 3; if (r[i] === team) points += 5; else exact = false; });
    if (p.length && r.length && exact && p.length === r.length) points += bonus;
  });
  return points;
}
